version = "1"

name = "Nix"
description = "Lints and suggestions for the Nix programming language"
category = "language"
visibility = "public"
analysis_command = "/app/statix check -o marvin $CODE_PATH > /toolbox/analysis_results.json"

[analyzer]
command = "/app/statix check -o marvin $CODE_PATH > /toolbox/analysis_results.json"

[build]
image = "ubuntu:18.04"
steps = """
apt-get update
apt-get install -y build-essential curl openssl
curl https://sh.rustup.rs -sSf | bash -s -- -y
.cargo/bin/cargo build --release
cp ./target/release/statix /app/statix
"""
