version = "1"

name = "Nix"
description = "Lints and suggestions for the Nix programming language"
category = "language"
visibility = "public"
analysis_command = "/app/statix check -o marvin $CODE_PATH > /toolbox/analysis_results.json"

[analyzer]
command = "/app/statix check -o marvin $CODE_PATH > /toolbox/analysis_results.json"

[build]
image = "nixos/nix"
steps = """
nix-env -iA cachix -f https://cachix.org/api/v1/install
cachix use statix
nix-build
cp ./result/bin/statix /app/statix
"""
