title = "Found usage of deprecated builtin isNull"
severity = "minor"
category = "antipattern"
description = """
Checks for usage of the `isNull` function.

## Why is this bad?
`isNull` is deprecated.

## Example

Instead of `isNull` for `null` checks,

```nix
isNull e
```

use the equality operator:

```nix
e == null
```
"""
weight=40
