title = "Found lib.groupBy"
severity = "minor"
category = "antipattern"
description = """
Checks for `lib.groupBy`.

## Why is this bad?
Nix 2.5 introduces `builtins.groupBy` which is faster and does
not require a lib import.

## Example

```nix
lib.groupBy (x: if x > 2 then "big" else "small") [ 1 2 3 4 5 6 ];
# { big = [ 3 4 5 6 ]; small = [ 1 2 ]; }
```

Replace `lib.groupBy` with `builtins.groupBy`:

```nix
builtins.groupBy (x: if x > 2 then "big" else "small") [ 1 2 3 4 5 6 ];
```
"""
weight=40
