title = "Useless let-in expression"
severity = "minor"
category = "antipattern"
description = """
Checks for `let-in` expressions which create no new bindings.

<!--more-->

## Why is this bad?
`let-in` expressions that create no new bindings are useless.
These are probably remnants from debugging or editing expressions.

## Example

```nix
let in pkgs.statix
```

Preserve only the body of the `let-in` expression:

```nix
pkgs.statix
```
"""
weight=40

