title = "Using undocumented `let` syntax"
severity = "minor"
category = "antipattern"
description = """
Checks for legacy-let syntax that was never formalized.

## Why is this bad?
This syntax construct is undocumented, refrain from using it.

## Example

Legacy let syntax makes use of an attribute set annotated with
`let` and expects a `body` attribute.
```nix
let {
  body = x + y;
  x = 2;
  y = 3;
}
```

This is trivially representible via `rec`, which is documented
and more widely known:

```nix
rec {
  body = x + y;
  x = 2;
  y = 3;
}.body
```
"""
weight=40
