title = "Assignment instead of inherit from"
severity = "minor"
category = "antipattern"
description = """
Checks for bindings of the form `a = someAttr.a`.

## Why is this bad?
If the aim is to extract or bring attributes of an attrset into
scope, prefer an inherit statement.

## Example

```nix
let
  mtl = pkgs.haskellPackages.mtl;
in
  null
```

Try `inherit` instead:

```nix
let
  inherit (pkgs.haskellPackages) mtl;
in
  null
```
"""
weight=40

